
title: Chaeyoung Lee
description:
baseurl: ""
url: "https://chaeyoung-lee.github.io"
theme: minima

# Add navigation links
minima:
  navigation:
    - title: "About"
      url: "/about/"
    - title: "Research"
      url: "/research/"
    - title: "Teaching"
      url: "/teaching/"
    - title: "Blog"
      url: "/blog/"