
title: Chae Young Lee
description: Chae Young Lee's personal website
baseurl: ""
url: "https://chaeyoung-lee.github.io"
theme: minima

# Add navigation links
minima:
  navigation:
    - title: "About"
      url: "/"
    - title: "Research"
      url: "/research/"
    - title: "Teaching"
      url: "/teaching/"
